### ISSUE TITLE
Can we get a build?

### ISSUE THREAD

**Issue by scunningham** [nats-io/python-nats#28]
The hard dependency on tornado 4.2 in v0.5.4 is problematic.  Can we get a new tag and a build pushed up to pypi.python.org?  Thanks.

**Comment by wallyqs** [comment]
ok! can you send PR with the preferred dependency to be locked or to relax it? I'll make a new build and release today then, thanks!

**Comment by scunningham** [comment]
Thanks!
The important requirement was already relaxed in a previous commit:
https://github.com/nats-io/python-nats/commit/29a76a5636d6a1b15d57857a26481e7d615ae2a0

I submitted a PR to pick up the change in requirements.txt for completeness.

**Comment by wallyqs** [comment]
Ah, right! OK making a new release later today. Thanks!

**Comment by wallyqs** [comment]
Just release `v0.5.6` version of the client including this. https://github.com/nats-io/python-nats/releases/tag/v0.5.6 
Thanks for the contribution.
