### ISSUE TITLE
Can't pip install nats-client

### ISSUE THREAD

**Issue by charliestrawn-wf** [nats-io/python-nats#3]
When trying to `pip install nats-client` I receive the following error:

```bash
$ pip install nats-client
Collecting nats-client
  Using cached nats_client-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lk/ymzwyyv92z11zmxqlct6phq80000gp/T/pip-build-Xwfa7s/nats-client/setup.py", line 2, in <module>
        from nats.io.client import __version__
      File "nats/__init__.py", line 1, in <module>
        from nats.io.client import Client
      File "nats/io/client.py", line 7, in <module>
        import tornado.iostream
    ImportError: No module named tornado.iostream

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lk/ymzwyyv92z11zmxqlct6phq80000gp/T/pip-build-Xwfa7s/nats-client
```
Steps to reproduce:
1. create a new virtualenv
2. pip install nats-client

As a consumer of this library, I would expect to be able to list nats-client in my requirements.txt file and be able to pip install it from there.  I'm happy to help out debugging anyway I can.

Thanks,
Charlie

**Comment by tylertreat** [comment]
The problem is setup.py is importing `__version__` which also imports tornado, which hasn't been installed by setup yet. I solve this problem by doing something like this: https://github.com/tylertreat/BigQuery-Python/blob/master/setup.py#L5-L8
